# https://github.com/Klipper3d/klipper/blob/master/klippy/reactor.py

from typing import Callable

class ReactorTimer: ...

_NOW: float
_NEVER: float

class ReactorCompletion:
    class sentinel: ...

    def test(self) -> bool: ...
    def complete(self, result: object) -> None: ...
    def wait(
        self, waketime: float = _NEVER, waketime_result: object = None
    ) -> object: ...

class Reactor:
    NOW: float
    NEVER: float
    monotonic: Callable[[], float]
    def register_timer(
        self, callback: Callable[[float], float], waketime: float = NEVER
    ) -> ReactorTimer: ...
    def update_timer(self, timer_handler: ReactorTimer, waketime: float) -> None: ...
    def register_async_callback(
        self, callback: Callable[[float], None], waketime: float = NOW
    ) -> None: ...
    def pause(self, waketime: float) -> float: ...
    def completion(self) -> ReactorCompletion: ...
