from typing import Callable, Protocol, Tuple, TypedDict
from configfile import ConfigWrapper
from gcode import GCodeCommand
from mcu import MCU_endstop

HINT_TIMEOUT: str

class _ProbeStatus(TypedDict):
    name: str
    last_query: bool | int
    last_z_result: float

class ProbeCommandHelper:
    def __init__(
        self,
        config: ConfigWrapper,
        probe: object,
        query_endstop: Callable[[float], int] | None = None,
    ) -> None: ...
    def get_status(self, eventtime: float) -> _ProbeStatus: ...

class ProbeOffsetsHelper:
    def __init__(self, config: ConfigWrapper) -> None: ...
    def get_offsets(self) -> Tuple[float, float, float]: ...

class _ProbeSession(Protocol): ...

class _ProbeParams(TypedDict):
    probe_speed: float
    lift_speed: float
    samples: int
    sample_retract_dist: float
    samples_tolerance: float
    samples_tolerance_retries: int
    samples_result: float

class ProbeSessionHelper:
    def __init__(
        self, config: ConfigWrapper, mcu_probe: ProbeEndstopWrapper
    ) -> None: ...
    def start_probe_session(self, gcmd: GCodeCommand) -> _ProbeSession: ...
    def end_probe_session(self) -> None: ...
    def get_probe_params(self, gcmd: GCodeCommand | None = None) -> _ProbeParams: ...
    def run_probe(self, gcmd: GCodeCommand) -> None: ...
    def pull_probed_results(self) -> list[float]: ...

class ProbeEndstopWrapper(MCU_endstop, Protocol):
    def multi_probe_begin(self) -> None: ...
    def multi_probe_end(self) -> None: ...
    def probing_move(self, pos: list[float], speed: float) -> list[float]: ...
    def probe_prepare(self, hmove: float) -> None: ...
    def probe_finish(self, hmove: float) -> None: ...
    def get_position_endstop(self) -> float: ...

class PrinterProbe(Protocol):
    def get_probe_params(self, gcmd: GCodeCommand | None = None) -> _ProbeParams: ...
    def get_offsets(self) -> Tuple[float, float, float]: ...
    def get_status(self, eventtime: float) -> _ProbeStatus: ...
    def start_probe_session(self, gcmd: GCodeCommand) -> _ProbeSession: ...
